export const NEARBY_STATIONS_REQUEST = 'NEARBY_STATIONS_REQUEST';
export const NEARBY_STATIONS_SUCCESS = 'NEARBY_STATIONS_SUCCESS';
export const NEARBY_STATIONS_ERROR = 'NEARBY_STATIONS_ERROR';

export const USER_LOCATION_REQUEST = 'USER_LOCATION_REQUEST';
export const USER_LOCATION_SUCCESS = 'USER_LOCATION_SUCCESS';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';
